# Generated by Django 5.0.7 on 2024-10-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('informacoes', models.TextField()),
                ('requisitos', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='cursos/imagens/')),
                ('galeria_fotos', models.ImageField(blank=True, null=True, upload_to='cursos/galeria/')),
            ],
        ),
    ]
