# Generated by Django 5.0.7 on 2024-10-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='galeria_fotos',
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='totem/images'),
        ),
    ]
