# Generated by Django 5.0.7 on 2024-10-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0003_remove_curso_galeria_fotos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='video',
        ),
    ]
