# Generated by Django 5.0.7 on 2024-10-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0007_curso_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagem_principal',
        ),
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cursos/'),
        ),
    ]
