# Generated by Django 5.0.7 on 2024-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0008_remove_curso_imagem_principal_curso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
