# Generated by Django 5.0.7 on 2024-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0009_alter_curso_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link_informacoes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='link_interesses',
            field=models.URLField(blank=True, null=True),
        ),
    ]
