# Generated by Django 5.1.2 on 2024-10-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0010_curso_link_informacoes_curso_link_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aprendizagem_continuada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='aprendizagem_industrial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='gratuitos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='presencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='tecnicos',
            field=models.BooleanField(default=False),
        ),
    ]
