# Generated by Django 5.1.2 on 2024-10-29 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totem', '0011_curso_aprendizagem_continuada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('num_cliques', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totem.curso')),
            ],
        ),
    ]
